//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoChoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id_admin { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public Nullable<int> id_nv { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
