//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoChoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int id_HD { get; set; }
        public int id_SP { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> tongTien { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
